version: "3.8"

services:
  api:
    image: carto/geoapp
    build:
      context: .
      target: backend
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    
  db:
    image: postgis/postgis:10-2.5-alpine
    env:
      POSTGRES_DB: carto
      POSTGRES_USER: carto
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/PGDATA
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
