version: "3.8"

services:
  api:
    image: eudg956/geoapp
    build:
      context: .
      target: backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    
  db:
    image: postgis/postgis:10-2.5-alpine
    environment:
      POSTGRES_DB: carto
      POSTGRES_USER: carto
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/PGDATA
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data:/var/lib/postgresql/csv_imports

volumes:
  postgres_data:
