db_config:
  database_class: PostgresDatabase
  host: db
  database: carto
  user: carto
  password: password
data:
  payments: "/var/lib/postgresql/csv_imports/paystats.csv"
  postalcodes: "/var/lib/postgresql/csv_imports/postal_codes.csv"
